'use client';

import { Card, CertaintyTag, Source } from './Ui';
import { formatBn, taka, toBnDigits } from '@/lib/payscale/format';
import type { FixationResult } from '@/lib/payscale/types';

/**
 * "এই বেতন কীভাবে নির্ধারণ হলো?" — the step-by-step explanation.
 *
 * Each step shows what it produced *and why*, because the "why" is the part
 * somebody can argue with. The formula line is generated by the engine from
 * the values it actually used, so it cannot drift away from the result the way
 * a hand-written illustration would.
 */
export function SalaryFixationDetails({ result }: { result: FixationResult }) {
  if (result.steps.length === 0) return null;

  return (
    <Card>
      <h3 className="text-subheading text-ink">এই বেতন কীভাবে নির্ধারণ হলো?</h3>
      <p className="mt-1 text-small text-ink-muted">
        প্রতিটি ধাপে কোন বিধি প্রয়োগ হইয়াছে এবং কেন, তাহা নিচে দেওয়া হইল।
      </p>

      <ol className="mt-4 space-y-3">
        {result.steps.map((step) => (
          <li key={step.step} className="relative rounded-control border border-border bg-surface-sunken p-3.5">
            <div className="flex flex-wrap items-center gap-2">
              <span
                aria-hidden="true"
                className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full
                           bg-accent-soft text-micro font-semibold text-accent-ink tabular-nums"
              >
                {toBnDigits(step.step)}
              </span>
              <span className="text-small font-semibold text-ink">{step.title}</span>
              <CertaintyTag value={step.certainty} />
            </div>

            {step.value !== undefined ? (
              <p className="mt-2 font-bengali text-subheading tabular-nums text-ink">
                {taka(step.value)}
              </p>
            ) : null}

            <p className="mt-1.5 text-small text-ink-muted">{step.why}</p>

            {step.formula ? (
              <p className="mt-2 overflow-x-auto rounded border border-border bg-surface px-2.5 py-1.5
                            font-bengali text-small tabular-nums text-ink">
                {step.formula}
              </p>
            ) : null}

            {step.source ? <Source source={step.source} compact /> : null}
          </li>
        ))}
      </ol>
    </Card>
  );
}

/** "হিসাবের সূত্র দেখুন" — the chain of operations, built from the values the
 *  engine used. Never a decorative formula. */
export function FormulaViewer({ result }: { result: FixationResult }) {
  if (!result.ok || result.newScale === null || result.oldScale === null) return null;

  const chain: { label: string; value: string }[] = [
    { label: 'পুরাতন Basic (৩০ জুন ২০২৬)', value: taka(result.input.currentBasic) },
    {
      label: '২০১৫ সালের বিশেষ সুবিধা / Adjustment',
      value: 'প্রযোজ্য নয় — অনুচ্ছেদ ১(৩)(ট)',
    },
  ];

  if (result.stepDifference !== null && result.stepDifference > 0) {
    chain.push({
      label: 'ধাপ পার্থক্য (অনুচ্ছেদ ৫(খ))',
      value: `${formatBn(result.input.currentBasic)} − ${formatBn(result.oldScale.minimum)} = ${formatBn(result.stepDifference)}`,
    });
    chain.push({
      label: 'Fixation Base',
      value: `${formatBn(result.newScale.minimum)} + ${formatBn(result.stepDifference)} = ${formatBn(result.fixationBase ?? 0)}`,
    });
  } else {
    chain.push({
      label: 'Fixation Base (অনুচ্ছেদ ৫(ক))',
      value: `অনুরূপ স্কেলের প্রারম্ভিক ধাপ = ${formatBn(result.newScale.minimum)}`,
    });
  }

  chain.push({
    label: 'অনুরূপ স্কেলের ধাপে নির্ধারণ',
    value: taka(result.fixedBasic),
  });

  if (result.incrementApplied && result.incrementAmount !== null) {
    chain.push({
      label: '১ জুলাই ২০২৬ — ১টি বার্ষিক বেতনবৃদ্ধি (অনুচ্ছেদ ৯(২))',
      value: `${formatBn(result.fixedBasic ?? 0)} + ${formatBn(result.incrementAmount)} = ${formatBn(result.newBasic ?? 0)}`,
    });
  }

  chain.push({ label: 'নতুন Basic', value: taka(result.newBasic) });

  return (
    <details className="group rounded-card border border-border bg-surface">
      <summary className="cursor-pointer list-none px-4 py-3.5 text-subheading text-ink marker:hidden">
        <span className="flex items-center justify-between gap-4">
          হিসাবের সূত্র দেখুন
          <span aria-hidden="true" className="shrink-0 text-ink-subtle transition-transform group-open:rotate-45">+</span>
        </span>
      </summary>
      <div className="border-t border-border px-4 py-4">
        <ol className="space-y-2">
          {chain.map((row, i) => (
            <li key={row.label} className="flex flex-col gap-0.5 sm:flex-row sm:items-baseline sm:justify-between sm:gap-4">
              <span className="text-small text-ink-muted">
                <span aria-hidden="true" className="mr-1.5 text-ink-subtle">{i === 0 ? '' : '→'}</span>
                {row.label}
              </span>
              <span className="font-bengali text-small tabular-nums text-ink">{row.value}</span>
            </li>
          ))}
        </ol>
      </div>
    </details>
  );
}
