import type { Metadata } from 'next';

/**
 * One place that decides what every page tells a search engine.
 *
 * This exists because of a bug it now prevents. The root layout used to carry
 * `alternates: { canonical: '/' }`, which Next inherits into every page that
 * does not override it — so /search, /sign-in, /sign-up and even the 404 page
 * all declared themselves canonical to the homepage. That is not a missing
 * optimisation; it actively tells Google those URLs ARE the homepage.
 *
 * So: the layout sets no canonical at all, and every page builds its metadata
 * through here, where canonical is a required decision rather than something
 * inherited by accident.
 */

export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ?? 'https://pickixo.com'
).replace(/\/$/, '');

export const SITE_NAME = 'Pickixo';

export const SITE_TAGLINE =
  'AI, Apps, Tools, Games, Jobs & Education — All in One Place';

export const SITE_DESCRIPTION =
  'One account for AI, apps, tools, games, jobs and education. Free to use, ' +
  'with the products you use most kept together in My Apps.';

/** Absolute URL for a site-relative path. Sitemap, canonical and og:url must
 *  all agree, so they all come through this. */
export function absoluteUrl(path: string): string {
  if (path.startsWith('http')) return path;
  return `${SITE_URL}${path.startsWith('/') ? path : `/${path}`}`;
}

/**
 * The default social card, generated by scripts/make-og-image.py.
 *
 * A static file rather than a per-request render: next/og crashes on Windows
 * (@vercel/og cannot parse the path it hands fileURLToPath), and on a 4 GB box
 * not rendering an image on every share is the better trade regardless.
 * Re-run that script if the brand colours change.
 */
export const DEFAULT_OG_IMAGE = '/og.png';

type SeoInput = {
  /** Page title, without the site suffix — the template adds that. */
  title: string;
  description: string;
  /** Site-relative path. Required: a page that cannot name its own canonical
   *  URL has no business being indexable. */
  path: string;
  /** Set false for pages that exist but should not be in an index: search
   *  results, auth screens, anything thin or private. They stay crawlable so
   *  the noindex is actually seen (§25). */
  index?: boolean;
  /** og:type. 'website' for listings, 'article' for written content. */
  type?: 'website' | 'article';
  /** Overrides the generated social image. */
  image?: string;
  publishedTime?: string;
  modifiedTime?: string;
};

export function buildMetadata({
  title,
  description,
  path,
  index = true,
  type = 'website',
  image,
  publishedTime,
  modifiedTime,
}: SeoInput): Metadata {
  const url = absoluteUrl(path);
  // Absolute, because every consumer of og:image resolves it independently and
  // a relative URL is the most common reason a card renders blank.
  const images = [
    {
      url: absoluteUrl(image ?? DEFAULT_OG_IMAGE),
      width: 1200,
      height: 630,
      alt: `${SITE_NAME} — ${SITE_TAGLINE}`,
    },
  ];

  return {
    title,
    description,
    alternates: { canonical: url },
    robots: index
      ? { index: true, follow: true,
          googleBot: { index: true, follow: true, 'max-image-preview': 'large',
                       'max-snippet': -1, 'max-video-preview': -1 } }
      : { index: false, follow: true },
    openGraph: {
      title,
      description,
      url,
      siteName: SITE_NAME,
      type,
      locale: 'en_US',
      images,
      ...(publishedTime ? { publishedTime } : {}),
      ...(modifiedTime ? { modifiedTime } : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images,
    },
  };
}

// ---------------------------------------------------------------------------
// Structured data
//
// Everything below describes something a visitor can actually see on the page.
// No ratings, no prices that are not real, no claims the page does not make.
// ---------------------------------------------------------------------------

/** Stable @id values so the graph nodes can reference each other. */
export const ORGANIZATION_ID = `${SITE_URL}/#organization`;
export const WEBSITE_ID = `${SITE_URL}/#website`;

export function organizationSchema() {
  return {
    '@type': 'Organization',
    '@id': ORGANIZATION_ID,
    name: SITE_NAME,
    url: `${SITE_URL}/`,
    description: SITE_DESCRIPTION,
    logo: {
      '@type': 'ImageObject',
      url: absoluteUrl('/icon.svg'),
    },
  };
}

export function websiteSchema() {
  return {
    '@type': 'WebSite',
    '@id': WEBSITE_ID,
    name: SITE_NAME,
    url: `${SITE_URL}/`,
    description: SITE_DESCRIPTION,
    publisher: { '@id': ORGANIZATION_ID },
    inLanguage: 'en',
    // Declared because the site really does have a working search at /search
    // that accepts this parameter. It is not decoration.
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: `${SITE_URL}/search?q={search_term_string}`,
      },
      'query-input': 'required name=search_term_string',
    },
  };
}

export function breadcrumbSchema(
  trail: { name: string; path: string }[],
) {
  return {
    '@type': 'BreadcrumbList',
    itemListElement: trail.map((crumb, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: crumb.name,
      item: absoluteUrl(crumb.path),
    })),
  };
}

/**
 * SoftwareApplication for a product that is actually usable.
 *
 * Never emitted for a product still marked `planned`: describing something as a
 * free WebApplication when the page says "this is not built yet" is a
 * structured-data claim the page does not support, and Google treats that as
 * spam rather than as optimism.
 */
export function softwareApplicationSchema(app: {
  name: string;
  description: string;
  url: string;
  category?: string;
}) {
  return {
    '@type': 'SoftwareApplication',
    name: app.name,
    description: app.description,
    url: absoluteUrl(app.url),
    applicationCategory: app.category ?? 'UtilitiesApplication',
    operatingSystem: 'Any',
    browserRequirements: 'Requires a modern web browser',
    isAccessibleForFree: true,
    offers: {
      '@type': 'Offer',
      price: '0',
      priceCurrency: 'USD',
      availability: 'https://schema.org/InStock',
    },
    publisher: { '@id': ORGANIZATION_ID },
  };
}

/** Wraps nodes into one @graph, which is how the pieces reference each other. */
export function jsonLd(...nodes: object[]) {
  return JSON.stringify({
    '@context': 'https://schema.org',
    '@graph': nodes,
  });
}
